### ISSUE TITLE
The following packages did not export their

### ISSUE THREAD

**Issue by yokhen** [josefaidt/svelte-themer#35]
## Setup info
I have installed through `yarn add -D svelte-themer`, however I have also tried adding as a normal dependency and nothing changed.

## Errors

At build time I get the following
```
[rollup-plugin-svelte] The following packages did not export their `package.json` file so we could not check the "svelte" field. If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.

- svelte-themer
```

When I try to access the website I get the following:
```
Error: <ThemeWrapper> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at validate_component (/.../project/__sapper__/dev/server/server.js:95:15)
    at /.../project/__sapper__/dev/server/server.js:15381:3
    at Object.$$render (/.../project/__sapper__/dev/server/server.js:113:22)
    at /.../project/__sapper__/dev/server/server.js:15438:40
    at $$render (/.../project/__sapper__/dev/server/server.js:113:22)
    at Object.render (/.../project/__sapper__/dev/server/server.js:121:26)
    at /.../project/__sapper__/dev/server/server.js:20314:49
    at Generator.next (<anonymous>)
    at fulfilled (/.../project/__sapper__/dev/server/server.js:15757:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: <ThemeWrapper> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at validate_component (/.../project/__sapper__/dev/server/server.js:95:15)
    at /.../project/__sapper__/dev/server/server.js:15381:3
    at Object.$$render (/.../project/__sapper__/dev/server/server.js:113:22)
    at /.../project/__sapper__/dev/server/server.js:15438:40
    at $$render (/.../project/__sapper__/dev/server/server.js:113:22)
    at Object.render (/.../project/__sapper__/dev/server/server.js:121:26)
    at /.../project/__sapper__/dev/server/server.js:20314:49
    at Generator.next (<anonymous>)
    at fulfilled (/.../project/__sapper__/dev/server/server.js:15757:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: <ThemeWrapper> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at validate_component (/.../project/__sapper__/dev/server/server.js:95:15)
    at /.../project/__sapper__/dev/server/server.js:15381:3
    at Object.$$render (/.../project/__sapper__/dev/server/server.js:113:22)
    at /.../project/__sapper__/dev/server/server.js:15438:40
    at $$render (/.../project/__sapper__/dev/server/server.js:113:22)
    at Object.render (/.../project/__sapper__/dev/server/server.js:121:26)
    at /.../project/__sapper__/dev/server/server.js:20314:49
    at Generator.next (<anonymous>)
    at fulfilled (/.../project/__sapper__/dev/server/server.js:15757:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**Comment by josefaidt** [comment]
Hey @yokhen :wave: thanks for raising this! I feel like I am constantly battling this error despite changing build configs (same with the package.json warning, that one is confusing). I believe you can get around this by importing the component directly with `svelte-themer/components/ThemeWrapper.svelte`, but it is something I'm looking at fixing for good.

**Comment by rarenatoe** [comment]
Thanks. Will do.

**Comment by josefaidt** [comment]
Hey :wave: apologies for the long delay, but looks like your fix resolved this issue! Thank you for that! Closing issue :)
